---                                                        
 - hosts: all                                              
   tasks:                                                  
     - name: Instalar Nginx                                
       apt: name=nginx state=present update_cache=yes  

