---                                                
- hosts: all                                       
  tasks:
    - name: Buscando nome dos servidores                                           
      command: hostname  
